---
swagger: '2.0'
info:
  title: API V1. Documentation for Kinedu api test
  version: v1
securitySchemes:
  basic_auth:
    type: http
    scheme: basic
paths:
  "/api/sessions":
    post:
      summary: Login method
      description: |-
        The user should provide his/hers email and password.
              The request will return the auth_token needed to authorize the other requests
      tags:
      - Sessions
      consumes:
      - application/json
      parameters:
      - name: params
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
            required:
            - email
            - password
      produces:
      - application/json
      responses:
        '200':
          description: with valid user credentials
          examples:
            application/json:
              data:
                id: '4'
                type: users
                attributes:
                  auth-token: N4zQ5dqNyRiS6YUFj3UfPeTd
                  expires-at: '2020-08-05T00:38:13.000+0000'
        '401':
          description: with invalid user credentials
          examples:
            application/json:
              message: Bad credentials
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
